# -*- coding: utf-8 -*-
"""Customer_Shopping_Retail_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBeM4nr1eXILwesBW8_6EZTPelk4Ahes
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

df=pd.read_csv(r'/content/customer_shopping_data.csv')

df.shape

print(f"The total number of purchaes are {df['invoice_no'].shape[0]}")

df.dtypes

df['invoice_date']=pd.to_datetime(df['invoice_date'],format='%d/%m/%Y')

df.dtypes

df.head(7)

int(df.duplicated().sum())

df.isna().sum()

df[['age','quantity','price']].describe()

for col in ['age','quantity','price']:
  plt.figure(figsize=(10,10))
  sns.boxplot(df[col])
  plt.show()

plt.figure(figsize=(10,10))
plt.scatter(df['category'],df['price'])
plt.show()

plt.figure(figsize=(10,10))
plt.scatter(df['shopping_mall'],df['price'])
plt.xticks(rotation=45)
plt.show()

df['revenque']=df['quantity']*df['price']

ageMean=float(df['age'].mean())
ageMean

totalRevenque1=0
for i in df.index:
  if df.iloc[i]['age']<=ageMean:
    totalRevenque1+=df.iloc[i]['revenque']

print(totalRevenque1)

totalRevenque2=0
for i in df.index:
  if df.iloc[i]['age']>ageMean:
    totalRevenque2+=df.iloc[i]['revenque']

print(totalRevenque2)

if totalRevenque1>totalRevenque2:
  print(f"The category that  less than or equal {ageMean} has higher revenque")
else:
  print(f"The category that greather than {ageMean} has higher revenque")

bins = [0, 19, 39, 100]

labels = ['Teenagers', 'Young Adults', 'Seniors']

df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)
df.sample(30)

df['age_group'].value_counts()

df.groupby('age_group')['revenque'].sum()

df.groupby('age_group')['revenque'].sum().plot(kind='bar')
plt.xlabel('Age Group')
plt.ylabel('Total Revenue')
plt.title('Total Revenue by Age Group')
plt.xticks(rotation=45)
plt.show()

allCustomerAges=df['age'].unique().tolist()
allCustomerAges

categoryOne=df[df['age']<=19]
float(categoryOne['revenque'].sum())

#20-39
categoryTwo=df[(df['age']>=20) & (df['age']<=39)]
float(categoryTwo['revenque'].sum())

#40-65
categoryThree=df[(df['age']>=40) & (df['age']<=65)]
float(categoryThree['revenque'].sum())

#>65
categoryFour=df[df['age']>65]
float(categoryFour['revenque'].sum())

ageGroubCount={
    "13-19":categoryOne.shape[0],
    "20-39":categoryTwo.shape[0],
    "40-65":categoryThree.shape[0],
    ">65":categoryFour.shape[0]
}

plt.figure(figsize=(10,10))
plt.bar(ageGroubCount.keys(),ageGroubCount.values())
plt.xlabel('Age Group')
plt.ylabel('Number')
plt.title('Count each groub category')
plt.xticks(rotation=45)
plt.show()

ageGroubs={
    "13-19":float(categoryOne['revenque'].sum()),
    "20-39":float(categoryTwo['revenque'].sum()),
    "40-65":float(categoryThree['revenque'].sum()),
    ">65":float(categoryFour['revenque'].sum())
}

plt.figure(figsize=(10,10))
plt.bar(ageGroubs.keys(),ageGroubs.values())
plt.xlabel('Age Group')
plt.ylabel('Total Revenue')
plt.title('Total Revenue by Age Group')
plt.xticks(rotation=45)
plt.show()

dictionary4=categoryFour.groupby('gender')['revenque'].sum().to_dict()
dictionary4

plt.figure(figsize=(10,10))
plt.bar(dictionary4.keys(),dictionary4.values())
plt.xlabel('Gender')
plt.ylabel('Total Revenue')
plt.title('Total Revenue by Gender for >65')
plt.xticks(rotation=45)
plt.show()

dictionary1=categoryOne.groupby('gender')['revenque'].sum().to_dict()
dictionary1

plt.figure(figsize=(10,10))
plt.bar(dictionary1.keys(),dictionary1.values())
plt.xlabel('Gender')
plt.ylabel('Total Revenue')
plt.title('Total Revenue by Gender 13-39')
plt.xticks(rotation=45)
plt.show()

dictionary2=categoryTwo.groupby('gender')['revenque'].sum().to_dict()
dictionary2

plt.figure(figsize=(10,10))
plt.bar(dictionary2.keys(),dictionary2.values())
plt.xlabel('Gender')
plt.ylabel('Total Revenue')
plt.title('Total Revenue by Gender for 20-39')
plt.xticks(rotation=45)
plt.show()

dictionary3=categoryThree.groupby('gender')['revenque'].sum().to_dict()
dictionary3

plt.figure(figsize=(10,10))
plt.bar(dictionary3.keys(),dictionary3.values())
plt.xlabel('Gender')
plt.ylabel('Total Revenue')
plt.title('Total Revenue by Gender for 40-65')
plt.xticks(rotation=45)
plt.show()

genders=['Male','Female']
paymentMethods=df['payment_method'].unique().tolist()
paymentMethodCount={}
for gender in genders:
  currDictionary={}
  for paymentMethod in paymentMethods:
    df1=df[(df['gender']==gender) & (df['payment_method']==paymentMethod)]
    currDictionary[paymentMethod]=df[df['payment_method']==paymentMethod].shape[0]
  paymentMethodCount[gender]=currDictionary
paymentMethodCount

dicRes={}
for key in paymentMethodCount.keys():
  resFormat=""
  maxKey,maxValue="",float('-inf')
  for key1,val in paymentMethodCount[key].items():
    if val>maxValue:
      maxValue=val
      maxKey=key1

  resFormat=f"The payment method {maxKey} has highest use by {key}"
  dicRes[key]=resFormat

dicRes

df['shopping_mall'].unique().tolist()

len(df['shopping_mall'].unique().tolist())

shoppinMalTotalRevenues=df.groupby('shopping_mall')['revenque'].sum().to_dict()
shoppinMalTotalRevenues

plt.figure(figsize=(10,10))
plt.bar(shoppinMalTotalRevenues.keys(),shoppinMalTotalRevenues.values())
plt.xlabel('Shopping Mall')
plt.ylabel('Total Revenue')
plt.title('Total Revenue by Shopping Mall')
plt.xticks(rotation=45)
plt.show()

totalRevenue=float(df['revenque'].sum())
totalRevenue

percentageForEachShoppingMallOfTotalRevenque={}
for key,val in shoppinMalTotalRevenues.items():
  percentageForEachShoppingMallOfTotalRevenque[key]=(val/totalRevenue)*100
percentageForEachShoppingMallOfTotalRevenque

plt.figure(figsize=(10,10))
plt.bar(percentageForEachShoppingMallOfTotalRevenque.keys(),percentageForEachShoppingMallOfTotalRevenque.values())
plt.xlabel('Shopping Mall')
plt.ylabel('Percentage')
plt.title('Percentage of Total Revenue by Shopping Mall')
plt.xticks(rotation=45)
plt.show()

hoghestPercentageOfShoppingMall,maxPercentage="",float('-inf')
for key,val in percentageForEachShoppingMallOfTotalRevenque.items():
  if val>maxPercentage:
    maxPercentage=val
    hoghestPercentageOfShoppingMall=key

print(f"The mall {hoghestPercentageOfShoppingMall} has highest percentage revenque of total revenque with perecentage {maxPercentage}")

allYears,allMonths=df['invoice_date'].dt.year.unique().tolist(),df['invoice_date'].dt.month.unique().tolist()

allYears

allMonths

allMonths.sort()
allYears.sort()

yearlyRevenqueTotal={}
for year in allYears:
  df1=df[df['invoice_date'].dt.year==year]
  yearlyRevenqueTotal[year]=float(df1['revenque'].sum())
yearlyRevenqueTotal

highestYear,highestRevenque="",float('-inf')
for key,val in yearlyRevenqueTotal.items():
  if val>highestRevenque:
    highestRevenque=val
    highestYear=key

print(f"The year {highestYear} has highest revenque is {highestRevenque}")

ranges=np.arange(min(allYears),max(allYears)+1).tolist()
ranges

plt.figure(figsize=(10,10))
plt.bar(yearlyRevenqueTotal.keys(),yearlyRevenqueTotal.values())
plt.xlabel('Year')
plt.ylabel('Total Revenue')
plt.title('Total Revenue by Year')
plt.xticks(rotation=45)
plt.xticks(ranges)
plt.show()

yearPercentageRevenqueOfTotalRevenque={}
for key,val in yearlyRevenqueTotal.items():
  yearPercentageRevenqueOfTotalRevenque[key]=(val/totalRevenue)*100
yearPercentageRevenqueOfTotalRevenque

higestPercentageYear,highestPercentage="",float('-inf')
for key,val in yearPercentageRevenqueOfTotalRevenque.items():
  if val>highestPercentage:
    highestPercentage=val
    higestPercentageYear=key

print(f"The year {higestPercentageYear} has highest percentage revenque of total revenque with perecentage {highestPercentage}")

plt.figure(figsize=(10,10))
plt.bar(yearPercentageRevenqueOfTotalRevenque.keys(),yearPercentageRevenqueOfTotalRevenque.values())
plt.xlabel('Year')
plt.ylabel('Percentage')
plt.title('Percentage of Total Revenue by Year')
plt.xticks(rotation=45)
plt.xticks(ranges)
plt.show()

df.groupby(['shopping_mall', 'category'])['price'].agg(['mean', 'std', 'var']).reset_index()

pivot = pd.pivot_table(
    df,
    index=['shopping_mall', 'category'],
    values='price',
    aggfunc=['mean', 'std', 'var']
)

pivot = pivot.reset_index()
pivot

allCategories=df['category'].unique().tolist()

revenquesForEachCategory={}
for category in allCategories:
  df1=df[df['category']==category]
  revenquesForEachCategory[category]=float(df1['revenque'].sum())
revenquesForEachCategory

plt.figure(figsize=(10,10))
plt.bar(revenquesForEachCategory.keys(),revenquesForEachCategory.values())
plt.xlabel('Category')
plt.ylabel('Total Revenue')
plt.title('Total Revenue by Category')
plt.xticks(rotation=45)
plt.show()

revenquesForEachCategoryPerentage={}
for key,val in revenquesForEachCategory.items():
  revenquesForEachCategoryPerentage[key]=(val/totalRevenue)*100
revenquesForEachCategoryPerentage

plt.figure(figsize=(10,10))
plt.bar(revenquesForEachCategoryPerentage.keys(),revenquesForEachCategoryPerentage.values())
plt.xlabel('Category')
plt.ylabel('Percentage')
plt.title('Percentage of Total Revenue by Category')
plt.xticks(rotation=45)
plt.show()

revenqueForEachCategoryInEachYear={}
for year in allYears:
  currDic={}
  for category in allCategories:
    currDic[category]=float(df[(df['invoice_date'].dt.year==year) & (df['category']==category)]['revenque'].sum())
  revenqueForEachCategoryInEachYear[year]=currDic

revenqueForEachCategoryInEachYear

for year in revenqueForEachCategoryInEachYear.keys():
  highestCategory,highestRevenque="",float('-inf')
  for category,revenque in revenqueForEachCategoryInEachYear[year].items():
    if revenque>highestRevenque:
      highestRevenque=revenque
      highestCategory=category
  print(f"The year {year} has highest revenque of {highestCategory} with revenque {highestRevenque}")